[project]
enable_telemetry = true
user_env = []
session_timeout = 3600
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = true
auto_tag_thread = true
edit_message = false

[features.spontaneous_file_upload]
enabled = false
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
max_duration = 15000
chunk_duration = 1000
sample_rate = 44100

[UI]
name = "FDA Food Assistant"
default_collapse_content = false
cot = "full"

custom_css = "/public/styles.css"
custom_js = "/public/app.js"

[UI.theme]
default = "dark"
layout = "wide"

[UI.theme.light]
background = "#FFFFFF"
paper = "#111111"  # Darker grey for the panels
[UI.theme.light.primary]
main = "#000000"  # Full black text
[UI.theme.light.text]
primary = "#000000"  # Full black text
secondary = "#000000"  # Full black secondary text

[UI.theme.dark]
background = "#000000"  # Fully black background
paper = "#111111"  # Darker grey for the panels
[UI.theme.dark.primary]
main = "#FFFFFF"  # Fully white text
[UI.theme.dark.text]
primary = "#FFFFFF"  # Fully white text
secondary = "#FFFFFF"  # Fully white secondary text

[meta]
generated_by = "1.2.0"
